### ISSUE TITLE
HTML unique content: 2 index.html files

### ISSUE THREAD

**Issue by Juliebou** [Juliebou/code-a-website#1]
@hellachella

Markbot doesn't like that I have 2 index.html files in 2 different folders.
I have one in code-a-website folder and another one in the berries folder.

Should I rename one of them?
thanks!

**Comment by hellachella** [comment]
That is interesting because you have it right. Can you show me the markbot screen please?

**Comment by Juliebou** [comment]
I fixed it! the problem was that those 2 index.html files had the same title. So I just changed berries for berries details and now it is working.

**Comment by hellachella** [comment]
Ahhh!! Good eye.
